### ISSUE TITLE
Icon invisible on discord integration

### ISSUE THREAD

**Issue by P3RS3X** [AlexCatDev/Easy2D#1]
Icon is invis af cannot see, actually just nothing there poof fr, fix pls or my eyes will forever bleed

**Comment by AlexCatDev** [comment]
Skill issue

**Comment by AlexCatDev** [comment]
> Icon is invis af cannot see, actually just nothing there poof fr, fix pls or my eyes will forever bleed

Get quote github'd

**Comment by AlexCatDev** [comment]
![gredrick](https://user-images.githubusercontent.com/15963076/165527872-cfe2cbe5-6bf6-4c46-80ed-5db5e07453a8.gif)
